"""Split the generated header page into the two files the site uses.

    build/header.html  ->  layouts/partials/sea-header.html
                       ->  assets/css/sea-header.css

The header's own colour tokens are dropped: assets/css/tokens.css (from the
design system) provides them, so the header follows the site theme.
Run via `make header`; never edit the outputs by hand.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "build" / "header.html"
PARTIAL = ROOT / "layouts" / "partials" / "sea-header.html"
CSS = ROOT / "assets" / "css" / "sea-header.css"

BANNER = "GENERATED by tools/sea (make header). Do not edit by hand."


def main():
    html = SRC.read_text()
    style = html[html.index("<style>") + 7:html.index("</style>")]

    # Colour tokens come from tokens.css; keep only the geometry variables.
    style = re.sub(r"  @media \(prefers-color-scheme: dark\) \{\n    :root:not\(\[data-theme=\"light\"\]\) \{.*?\n    \}\n  \}\n", "", style, flags=re.S)
    style = re.sub(r"  :root\[data-theme=\"dark\"\] \{.*?\n  \}\n", "", style, count=1, flags=re.S)

    def keep_geometry(m):
        out = []
        for line in m.group(0).split("\n"):
            s = line.strip()
            if s.startswith("--") and not (s.startswith("--px") or s.startswith("--pier-w")):
                continue
            out.append(line)
        return "\n".join(out)

    style = re.sub(r"  :root \{\n.*?\n  \}", keep_geometry, style, count=1, flags=re.S)
    # Page-level rules belong to the site stylesheet, not the header.
    style = re.sub(r"  \* \{ box-sizing: border-box; \}\n", "", style)
    style = re.sub(r"  body \{.*?\n  \}\n", "", style, count=1, flags=re.S)
    style = re.sub(r"  /\* ---------- Demo only ---------- \*/.*", "", style, flags=re.S)
    for token in ("--sky: #", "--back: #", "--foam: #"):
        if token in style:
            sys.exit(f"split.py: colour token {token!r} survived; check the template")

    header = html[html.index('<header class="site-header"'):html.index("</header>") + 9]
    header = header.replace(
        '<p class="tagline">by the sea shore</p>',
        '<p class="tagline">by the sea shore</p>\n  <div class="motion-slot" id="motion-slot"></div>')

    PARTIAL.write_text(f"{{{{/* {BANNER} */}}}}\n{header}\n")
    CSS.write_text(f"/* {BANNER} */\n{style.strip()}\n")
    print(f"wrote {PARTIAL.relative_to(ROOT)} ({PARTIAL.stat().st_size} bytes)")
    print(f"wrote {CSS.relative_to(ROOT)} ({CSS.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
